export const TINYSLICE_ACTION_PREFIX = '[TinySlice]';
export const TINYSLICE_ACTION_INTERNAL_PREFIX = `${TINYSLICE_ACTION_PREFIX} [Internal]`;
export const TINYSLICE_ACTION_DEFAULT_PREFIX = `${TINYSLICE_ACTION_PREFIX} [Default]`;
